// Unit tests for p256-spki.js.
//
// Tests:
//   - Parses a valid SPKI generated by Node's `crypto.generateKeyPairSync`
//   - Rejects SPKI for the wrong curve (secp256k1)
//   - Rejects SPKI for the wrong key type (RSA)
//   - Rejects compressed-point encodings (0x02 / 0x03 prefix)
//   - Rejects truncated DER

import { test } from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";

import { parseP256Spki } from "./p256-spki.js";

test("parseP256Spki: parses a valid Node-generated P-256 SPKI", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  const { x, y } = parseP256Spki(spki);
  assert.equal(x.length, 32, "X must be 32 bytes");
  assert.equal(y.length, 32, "Y must be 32 bytes");
  // Sanity: an honest P-256 point will never be all zeros (zero is not
  // on the curve). This catches a parser that returns the wrong slice.
  assert.ok(x.some((b) => b !== 0), "X must not be all zeros");
  assert.ok(y.some((b) => b !== 0), "Y must not be all zeros");
});

test("parseP256Spki: rejects SPKI for the wrong curve (secp256k1)", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "secp256k1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  assert.throws(
    () => parseP256Spki(spki),
    /Curve OID:.*expected P-256.*got 1\.3\.132\.0\.10/,
  );
});

test("parseP256Spki: rejects SPKI for the wrong curve (P-384)", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "secp384r1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  assert.throws(
    () => parseP256Spki(spki),
    /Curve OID:.*expected P-256/,
  );
});

test("parseP256Spki: rejects RSA SPKI (wrong AlgorithmIdentifier OID)", () => {
  const { publicKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  assert.throws(
    () => parseP256Spki(spki),
    /AlgorithmIdentifier\.algorithm:.*expected ecPublicKey/,
  );
});

test("parseP256Spki: rejects truncated DER", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const full = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  // Snip the trailing point bytes — the parser must catch the length
  // overrun rather than returning whatever bytes happen to be there.
  const truncated = full.subarray(0, full.length - 5);
  assert.throws(() => parseP256Spki(truncated), /overruns DER|truncated/);
});

test("parseP256Spki: rejects empty input", () => {
  assert.throws(() => parseP256Spki(new Uint8Array(0)), /truncated DER/);
});

test("parseP256Spki: rejects non-Uint8Array input", () => {
  assert.throws(() => parseP256Spki("not bytes"), /expects a Uint8Array/);
  assert.throws(() => parseP256Spki(Buffer.from([])), /truncated DER/); // Buffer is a Uint8Array
});

test("parseP256Spki: rejects compressed-point encoding (0x02 prefix)", () => {
  // Construct a P-256 SPKI but flip the point's leading byte from
  // 0x04 (uncompressed) to 0x02 (compressed-even) and shrink to 33
  // bytes so the BIT STRING length matches a compressed point. The
  // parser also enforces a 65-byte point; we have to test BOTH the
  // wrong-prefix and the wrong-length error paths. This case targets
  // the prefix check, so we keep the 65-byte length and just flip the
  // first byte.
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  // The uncompressed point's 0x04 byte is at spki[spki.length - 65].
  const mutated = new Uint8Array(spki);
  mutated[mutated.length - 65] = 0x02;
  assert.throws(
    () => parseP256Spki(mutated),
    /expected uncompressed marker 0x04, got 0x2/,
  );
});

test("parseP256Spki: rejects compressed-point encoding (0x03 prefix)", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  const mutated = new Uint8Array(spki);
  mutated[mutated.length - 65] = 0x03;
  assert.throws(
    () => parseP256Spki(mutated),
    /expected uncompressed marker 0x04, got 0x3/,
  );
});

test("parseP256Spki: rejects wrong outer SEQUENCE tag", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const spki = new Uint8Array(publicKey.export({ type: "spki", format: "der" }));
  const mutated = new Uint8Array(spki);
  mutated[0] = 0x31; // SET instead of SEQUENCE
  assert.throws(
    () => parseP256Spki(mutated),
    /SPKI outer SEQUENCE: expected DER tag 0x30/,
  );
});
