#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${1:-mcp-server/.env.local}"
USDC_PRECOMPILE_ADDRESS="0x0000053900000000000000000000000001200000"

DWELLER_RPC_URL_VALUE="${DWELLER_RPC_URL:-}"
POLKADOT_RPC_URL_VALUE="${POLKADOT_RPC_URL:-}"
RPC_URL_VALUE="${RPC_URL:-${POLKADOT_RPC_URL_VALUE:-${DWELLER_RPC_URL_VALUE:-http://127.0.0.1:8545}}}"
SIGNER_KEY_VALUE="${SIGNER_PRIVATE_KEY:-${PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}}"

if [[ -n "${MOCK_DOT_ADDRESS:-}" && -z "${TOKEN_ADDRESS:-}" ]]; then
  TOKEN_ADDRESS_VALUE="$MOCK_DOT_ADDRESS"
  ASSET_SYMBOL_VALUE="${ASSET_SYMBOL:-DOT}"
  ASSET_CLASS_VALUE="${ASSET_CLASS:-custom}"
  ASSET_ID_VALUE="${ASSET_ID:-}"
  ASSET_DECIMALS_VALUE="${ASSET_DECIMALS:-18}"
else
  TOKEN_ADDRESS_VALUE="${TOKEN_ADDRESS:-$USDC_PRECOMPILE_ADDRESS}"
  ASSET_SYMBOL_VALUE="${ASSET_SYMBOL:-USDC}"
  ASSET_CLASS_VALUE="${ASSET_CLASS:-trust_backed}"
  ASSET_ID_VALUE="${ASSET_ID:-1337}"
  ASSET_DECIMALS_VALUE="${ASSET_DECIMALS:-6}"
fi

required_vars=(
  TREASURY_POLICY_ADDRESS
  AGENT_ACCOUNT_ADDRESS
  ESCROW_CORE_ADDRESS
  REPUTATION_SBT_ADDRESS
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "Missing required environment variable: $var_name" >&2
    exit 1
  fi
done

if [[ "$ASSET_CLASS_VALUE" == "custom" || -z "$ASSET_ID_VALUE" ]]; then
  SUPPORTED_ASSET_JSON="{\"symbol\":\"$ASSET_SYMBOL_VALUE\",\"assetClass\":\"$ASSET_CLASS_VALUE\",\"address\":\"$TOKEN_ADDRESS_VALUE\",\"decimals\":$ASSET_DECIMALS_VALUE}"
else
  SUPPORTED_ASSET_JSON="{\"symbol\":\"$ASSET_SYMBOL_VALUE\",\"assetClass\":\"$ASSET_CLASS_VALUE\",\"assetId\":$ASSET_ID_VALUE,\"address\":\"$TOKEN_ADDRESS_VALUE\",\"decimals\":$ASSET_DECIMALS_VALUE}"
fi

cat > "$OUTPUT_FILE" <<EOF
DWELLER_RPC_URL=$DWELLER_RPC_URL_VALUE
POLKADOT_RPC_URL=$POLKADOT_RPC_URL_VALUE
RPC_URL=$RPC_URL_VALUE
SIGNER_PRIVATE_KEY=$SIGNER_KEY_VALUE
TREASURY_POLICY_ADDRESS=$TREASURY_POLICY_ADDRESS
AGENT_ACCOUNT_ADDRESS=$AGENT_ACCOUNT_ADDRESS
ESCROW_CORE_ADDRESS=$ESCROW_CORE_ADDRESS
REPUTATION_SBT_ADDRESS=$REPUTATION_SBT_ADDRESS
DISCOVERY_REGISTRY_ADDRESS=${DISCOVERY_REGISTRY_ADDRESS:-}
XCM_WRAPPER_ADDRESS=${XCM_WRAPPER_ADDRESS:-}
STRATEGIES_JSON=${STRATEGIES_JSON:-[]}
SUPPORTED_ASSETS_JSON=[$SUPPORTED_ASSET_JSON]
SUPPORTED_ASSETS=$ASSET_SYMBOL_VALUE:$TOKEN_ADDRESS_VALUE
MUTATION_BACKEND=${MUTATION_BACKEND:-required}
EOF

echo "Wrote $OUTPUT_FILE"
