/**
 * Generated by scripts/generate-sdk-types.mjs.
 * Sources:
 * - sdk/api-surface-model.mjs
 * - mcp-server/src/core/job-schema-registry.js
 *
 * Do not edit this file manually. Update the source model or schema registry,
 * then run npm run generate:sdk-types.
 */

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };
export type WalletAddress = string;
export type AssetSymbol = string;
export type ISODateTime = string;
export type JobId = string;
export type SessionId = string;
export type IdempotencyKey = string;
export const DEFAULT_ESCROW_ASSET_SYMBOL: "USDC";

/**
 * Build a caller-side idempotency key suitable for the standard mutation contract.
 * Returns "<prefix>-<isoTimestamp>-<randomSuffix>". See docs/IDEMPOTENCY.md.
 */
export function createIdempotencyKey(prefix?: string): IdempotencyKey;

export interface AgentPlatformClientOptions {
  baseUrl: string;
  token?: string;
  fetchImpl?: typeof fetch;
}

export interface RequestOptions {
  method?: string;
  body?: unknown;
  headers?: HeadersInit;
}

export interface ApiEnvelope {
  [key: string]: unknown;
}

export interface HealthResponse extends ApiEnvelope {
  ok?: boolean;
  status?: string;
}

export interface OnboardingResponse extends ApiEnvelope {
  onboarding?: ApiEnvelope;
  entrypoint?: string;
}

export interface DiscoveryManifest extends ApiEnvelope {
  name?: string;
  version?: string;
  tools?: ApiEnvelope[];
  capabilities?: ApiEnvelope;
}

export interface JobTierLadderResponse extends ApiEnvelope {
  tiers?: ApiEnvelope[];
}

export interface StrategySummary extends ApiEnvelope {
  strategyId: string;
  id?: string;
  label?: string;
  asset?: AssetSymbol;
  kind?: string;
  riskLabel?: string;
}

export interface StrategiesResponse extends ApiEnvelope {
  strategies: StrategySummary[];
  docs?: string;
}

export interface SessionStateMachineResponse extends ApiEnvelope {
  statuses?: ApiEnvelope[];
  transitions?: ApiEnvelope[];
}

export interface JobSchemaSummary extends ApiEnvelope {
  name: string;
  path?: string;
  schema?: JsonObject;
}

export interface JobSchemasResponse extends ApiEnvelope {
  schemas?: JobSchemaSummary[];
}

export interface AgentProfile extends ApiEnvelope {
  wallet: WalletAddress;
  handle?: string;
  reputation?: number;
  badges?: ApiEnvelope[];
  currentActivity?: ApiEnvelope | null;
  lifetimeStats?: ApiEnvelope;
}

export interface AgentListResponse extends ApiEnvelope {
  agents?: AgentProfile[];
  count?: number;
}

export interface BadgeResponse extends ApiEnvelope {
  name?: string;
  description?: string;
  image?: string;
  attributes?: ApiEnvelope[];
}

export interface AlertListResponse extends ApiEnvelope {
  alerts?: ApiEnvelope[];
  count?: number;
}

export interface AuditEventListResponse extends ApiEnvelope {
  events?: ApiEnvelope[];
  count?: number;
}

export interface PolicySummary extends ApiEnvelope {
  tag: string;
  status?: string;
}

export interface PolicyListResponse extends ApiEnvelope {
  policies?: PolicySummary[];
}

export interface VerifierHandlersResponse extends ApiEnvelope {
  handlers?: ApiEnvelope[];
}

export interface NonceResponse extends ApiEnvelope {
  nonce?: string;
  message?: string;
}

export interface AuthSessionResponse extends ApiEnvelope {
  wallet?: WalletAddress;
  roles?: string[];
  capabilities?: string[];
}

export interface AssetBalances {
  [asset: AssetSymbol]: number;
}

export interface AccountSummary extends ApiEnvelope {
  wallet: WalletAddress;
  liquid?: AssetBalances;
  reserved?: AssetBalances;
  recurringTemplateReserves?: Record<JobId, { asset?: AssetSymbol; amount?: number }>;
  strategyAllocated?: AssetBalances;
  debtOutstanding?: AssetBalances;
}

export interface BorrowCapacityResponse extends ApiEnvelope {
  wallet?: WalletAddress;
  asset?: AssetSymbol;
  capacity?: number;
  available?: number;
}

export interface StrategyPositionsResponse extends ApiEnvelope {
  positions?: ApiEnvelope[];
}

export interface FundAccountInput {
  asset?: AssetSymbol;
  amount: number | string;
  idempotencyKey?: IdempotencyKey;
}

export interface StrategyMutationInput {
  asset?: AssetSymbol;
  amount: number | string;
  strategyId?: string;
  idempotencyKey?: IdempotencyKey;
  destination?: string;
  message?: string;
  maxWeight?: unknown;
  nonce?: number | string;
  recipient?: string;
}

export interface SendToAgentInput {
  recipient: WalletAddress;
  asset?: AssetSymbol;
  amount: number | string;
  idempotencyKey?: IdempotencyKey;
}

export interface BalanceMutationInput {
  asset?: AssetSymbol;
  amount: number | string;
  idempotencyKey?: IdempotencyKey;
}

export interface ClaimStatus extends ApiEnvelope {
  claimState?: string;
  effectiveState?: string;
  claimable?: boolean;
  currentWalletCanClaim?: boolean | null;
  reason?: string | null;
  retryLimit?: number | null;
  claimAttemptCount?: number | null;
  remainingClaimAttempts?: number | null;
  claimExpiresAt?: ISODateTime | null;
  expiredAt?: ISODateTime | null;
}

export interface DelegationPolicy extends ApiEnvelope {
  budgetAmount?: number;
  budgetAsset?: AssetSymbol;
  maxSubJobs?: number;
  maxDepth?: number;
}

export interface RecurringPolicy extends ApiEnvelope {
  reserveAmount?: number;
  reserveAsset?: AssetSymbol;
  maxRuns?: number;
  funding?: RecurringTemplateFunding;
}

export interface RecurringTemplateFunding extends ApiEnvelope {
  source?: "recurring_template_reserve" | string;
  wallet?: WalletAddress;
  asset?: AssetSymbol;
  amount?: number;
  amountRaw?: string;
  reservedAt?: ISODateTime;
  templateKey?: string;
}

export interface JobFunding extends ApiEnvelope {
  source?: "recurring_template_reserve" | string;
  templateId?: JobId;
  wallet?: WalletAddress;
  asset?: AssetSymbol;
  amount?: number;
  reservedAt?: ISODateTime;
  templateKey?: string;
}

/** Generic coding job input. */
export interface CodingInput {
  task: string;
  acceptanceCriteria: string[];
  repo?: string;
  files?: string[];
}

/** Generic coding job output. */
export interface CodingOutput {
  summary: string;
  output: string;
  status: "complete" | "partial" | "blocked";
  filesChanged?: string[];
}

/** GitHub pull request evidence for open-source issue jobs. */
export interface GithubPrEvidenceOutput {
  prUrl: string;
  summary: string;
  tests: string;
  notes?: string;
  prBody?: string;
  issueNumber?: number;
  issueUrl?: string;
  commitUrl?: string;
  branchUrl?: string;
  filesChanged?: string[];
  referencesIssue?: boolean;
  checksPassing?: boolean;
  ciStatus?: "unknown" | "pending" | "passing" | "failing";
  reviewApproved?: boolean;
  merged?: boolean;
}

/** Generic governance job input. */
export interface GovernanceInput {
  proposal: string;
  requestedOutcome: string;
  constraints?: string[];
}

/** Generic governance job output. */
export interface GovernanceOutput {
  summary: string;
  decisionSignal: "approve" | "reject" | "revise";
  recommendations?: string[];
}

/** PR or document review input. */
export interface ReviewInput {
  subject: string;
  reviewScope: string;
  rubric: string[];
  files?: string[];
}

/** Structured PR review findings. */
export interface PrReviewFindingsOutput {
  summary: string;
  findings: Array<{
    severity: "low" | "medium" | "high" | "critical";
    file: string;
    issue: string;
    recommendation: string;
  }>;
  risk_level: "low" | "medium" | "high";
  files_touched: string[];
  recommended_next_step: "merge" | "fix_and_retest" | "request_changes";
}

/** Release readiness review input. */
export interface ReleaseInput {
  release_id: string;
  checklist: string[];
  context?: string[];
}

/** Structured release go/no-go output. */
export interface ReleaseReadinessOutput {
  release_id: string;
  checks_passed: string[];
  checks_failed: string[];
  blockers: string[];
  go_no_go: "go" | "no_go";
}

/** Issue triage input. */
export interface TriageInput {
  report: string;
  routingOptions: string[];
  componentHints?: string[];
}

/** Structured issue triage output. */
export interface IssueDefectTriageOutput {
  category: "bug" | "ops" | "docs" | "governance" | "integration";
  severity: "low" | "medium" | "high" | "critical";
  component: "api" | "indexer" | "frontend" | "contracts" | "ops";
  repro_clarity: "clear" | "partial" | "unclear";
  next_owner: "backend" | "frontend" | "ops" | "contracts" | "docs";
  duplication_risk: "low" | "medium" | "high";
}

/** Documentation audit input. */
export interface DocsInput {
  surfaces: string[];
  goal: string;
  context?: string[];
}

/** Structured docs drift output. */
export interface DocsDriftAuditOutput {
  source_surface: string;
  drift_findings: Array<{
    surface_a: string;
    surface_b: string;
    mismatch: string;
  }>;
  missing_updates: string[];
  severity: "low" | "medium" | "high";
  fix_recommendation: string;
}

/** Dependency vulnerability remediation input from public advisory sources such as OSV/NVD. */
export interface DependencyRemediationInput {
  ecosystem: "npm";
  packageName: string;
  vulnerableVersion: string;
  fixedVersion: string;
  repo?: string;
  manifestPath?: string;
  advisoryIds: string[];
  advisoryUrls?: string[];
  instructions: string[];
}

/** Structured pull request evidence for a dependency vulnerability remediation. */
export interface DependencyRemediationOutput {
  prUrl: string;
  packageName: string;
  vulnerableVersion: string;
  fixedVersion: string;
  advisoryIds: string[];
  summary: string;
  tests: string;
  repo?: string;
  manifestPath?: string;
  lockfilesUpdated?: string[];
  filesChanged?: string[];
  ciStatus?: "unknown" | "pending" | "passing" | "failing";
  checksPassing?: boolean;
  notes?: string;
}

/** Public open-data dataset/resource quality audit input. */
export interface OpenDataQualityAuditInput {
  portal: "data.gov";
  datasetId?: string;
  datasetTitle: string;
  datasetUrl: string;
  resourceId?: string;
  resourceTitle?: string;
  resourceUrl: string;
  resourceFormat?: string;
  agency?: string;
  license?: string;
  modified?: string;
  metadataModified?: string;
  instructions: string[];
}

/** Structured evidence for a public open-data dataset/resource quality audit. */
export interface OpenDataQualityAuditOutput {
  dataset_title: string;
  dataset_url: string;
  resource_url: string;
  resource_format?: string;
  checks: Array<{
    name: string;
    status: "pass" | "warn" | "fail" | "unknown";
    evidence: string;
  }>;
  findings: Array<{
    severity: "low" | "medium" | "high";
    issue: string;
    evidence: string;
    recommendation: string;
  }>;
  no_issue_found: boolean;
  summary: string;
  recommended_actions: string[];
  notes?: string;
}

/** Public OpenAPI quality audit input. */
export interface OpenapiQualityAuditInput {
  apiTitle: string;
  specUrl: string;
  localSurface?: string;
  repo?: string;
  openapiVersion?: string;
  pathCount?: number;
  operationCount?: number;
  schemaCount?: number;
  instructions: string[];
}

/** Structured evidence for an OpenAPI spec quality audit. */
export interface OpenapiQualityAuditOutput {
  api_title: string;
  spec_url: string;
  local_surface?: string;
  openapi_version?: string;
  checks: Array<{
    name: string;
    status: "pass" | "warn" | "fail" | "unknown";
    evidence: string;
  }>;
  findings: Array<{
    severity: "low" | "medium" | "high";
    location: string;
    issue: string;
    evidence: string;
    recommendation: string;
  }>;
  no_issue_found: boolean;
  summary: string;
  recommended_actions: string[];
  notes?: string;
}

/** Wikipedia public article maintenance job input. */
export interface WikipediaMaintenanceInput {
  project: "wikipedia";
  language?: string;
  lang?: string;
  pageTitle: string;
  pageUrl: string;
  articleUrl?: string;
  revisionId: string;
  pinnedRevisionUrl?: string;
  taskType: "citation_repair" | "freshness_check" | "infobox_consistency";
  proposalOnly?: boolean;
  attributionPolicy?: string;
  outputSchemaUrl?: string;
  sourceUrls?: string[];
  instructions: string[];
}

/** Reviewable citation repair proposal for Wikipedia articles. */
export interface WikipediaCitationRepairOutput {
  page_title: string;
  revision_id: string;
  citation_findings: Array<{
    section: string;
    problem: "dead_link" | "missing_citation" | "weak_source" | "outdated_source" | "claim_mismatch";
    current_claim: string;
    evidence_url: string;
  }>;
  proposed_changes: Array<{
    change_type: "replace_citation" | "add_citation" | "flag_for_editor_review";
    target_text: string;
    replacement_text: string;
    source_url: string;
  }>;
  review_notes: string;
}

/** Freshness and factual drift check for a public Wikipedia article. */
export interface WikipediaFreshnessCheckOutput {
  page_title: string;
  revision_id: string;
  freshness_findings: Array<{
    claim: string;
    status: "current" | "outdated" | "unclear" | "needs_editor_review";
    evidence_url: string;
    note: string;
  }>;
  recommended_editor_actions: string[];
  risk_level: "low" | "medium" | "high";
}

/** Reviewable proposal for reconciling a Wikipedia infobox with cited article evidence. */
export interface WikipediaInfoboxConsistencyOutput {
  page_title: string;
  revision_id: string;
  checked_fields: Array<{
    field: string;
    current_value: string;
    evidence_url: string;
    status: "consistent" | "inconsistent" | "missing_source" | "needs_editor_review";
    note: string;
  }>;
  proposed_changes: Array<{
    field: string;
    target_text: string;
    replacement_text: string;
    source_url: string;
  }>;
  review_notes: string;
}

/** Structured evidence from the hosted product-proof worker loop. */
export interface ProductProofWorkerLoop {
  summary: string;
  output: string;
  status: "complete";
  job_id?: string;
  completed_at?: string;
  checks: Array<{
    name: string;
    status: "pass" | "warn" | "fail";
    evidence: string;
  }>;
}
export interface BuiltinJobSchemaMap {
  "schema://jobs/coding-input": CodingInput;
  "schema://jobs/coding-output": CodingOutput;
  "schema://jobs/github-pr-evidence-output": GithubPrEvidenceOutput;
  "schema://jobs/governance-input": GovernanceInput;
  "schema://jobs/governance-output": GovernanceOutput;
  "schema://jobs/review-input": ReviewInput;
  "schema://jobs/pr-review-findings-output": PrReviewFindingsOutput;
  "schema://jobs/release-input": ReleaseInput;
  "schema://jobs/release-readiness-output": ReleaseReadinessOutput;
  "schema://jobs/triage-input": TriageInput;
  "schema://jobs/issue-defect-triage-output": IssueDefectTriageOutput;
  "schema://jobs/docs-input": DocsInput;
  "schema://jobs/docs-drift-audit-output": DocsDriftAuditOutput;
  "schema://jobs/dependency-remediation-input": DependencyRemediationInput;
  "schema://jobs/dependency-remediation-output": DependencyRemediationOutput;
  "schema://jobs/open-data-quality-audit-input": OpenDataQualityAuditInput;
  "schema://jobs/open-data-quality-audit-output": OpenDataQualityAuditOutput;
  "schema://jobs/openapi-quality-audit-input": OpenapiQualityAuditInput;
  "schema://jobs/openapi-quality-audit-output": OpenapiQualityAuditOutput;
  "schema://jobs/wikipedia-maintenance-input": WikipediaMaintenanceInput;
  "schema://jobs/wikipedia-citation-repair-output": WikipediaCitationRepairOutput;
  "schema://jobs/wikipedia-freshness-check-output": WikipediaFreshnessCheckOutput;
  "schema://jobs/wikipedia-infobox-consistency-output": WikipediaInfoboxConsistencyOutput;
  "schema://jobs/product-proof-worker-loop": ProductProofWorkerLoop;
}

export type BuiltinJobSchemaRef = keyof BuiltinJobSchemaMap;
export type BuiltinJobSchemaValue<T extends BuiltinJobSchemaRef> = BuiltinJobSchemaMap[T];
export type StructuredSubmission = BuiltinJobSchemaMap[BuiltinJobSchemaRef] | JsonObject;

export interface SubmissionPayloadExample<TSubmission = StructuredSubmission> extends ApiEnvelope {
  sessionId?: SessionId | "<session-id>";
  submission: TSubmission;
}

export interface SubmissionContract<TSubmission = StructuredSubmission> extends ApiEnvelope {
  endpoint?: "POST /jobs/submit" | string;
  validationEndpoint?: "POST /jobs/validate-submission" | string;
  submissionShape?: "direct_schema_object" | string;
  structuredSubmissionRequired?: boolean;
  schemaValidates?: "payload.submission" | string;
  doNotWrapInOutput?: boolean;
  compatibilityAliases?: string[];
  outputSchemaRef?: BuiltinJobSchemaRef | string;
  outputSchemaUrl?: string;
  submitPayloadExample?: SubmissionPayloadExample<TSubmission>;
  invalidWrappedOutputHint?: string;
}

export interface SchemaContractSide extends ApiEnvelope {
  schemaRef?: BuiltinJobSchemaRef | string;
  schemaUrl?: string;
  knownBuiltin?: boolean;
  validates?: "payload.submission" | string;
  validationEndpoint?: "POST /jobs/validate-submission" | string;
}

export interface JobSchemaContract extends ApiEnvelope {
  input?: SchemaContractSide;
  output?: SchemaContractSide;
}

export interface JobDefinition extends ApiEnvelope {
  id: JobId;
  title?: string;
  category?: string;
  tier?: string;
  rewardAmount?: number;
  rewardAsset?: AssetSymbol;
  verifierMode?: string;
  retryLimit?: number;
  parentSessionId?: SessionId;
  delegationPolicy?: DelegationPolicy;
  recurringPolicy?: RecurringPolicy;
  claimStatus?: ClaimStatus;
  claimable?: boolean;
  claimState?: string;
  effectiveState?: string;
  currentWalletCanClaim?: boolean | null;
  reason?: string | null;
  submissionContract?: SubmissionContract;
  schemaContract?: JobSchemaContract;
  source?: ApiEnvelope;
  verification?: ApiEnvelope;
  lineage?: SubJobLineageMetadata;
  funding?: JobFunding;
}

export interface JobSummary extends ApiEnvelope {
  id: JobId;
  title?: string;
  category?: string;
  tier?: string;
  state?: string;
  status?: string;
  effectiveState?: string;
  claimState?: string;
  claimable?: boolean;
  currentWalletCanClaim?: boolean | null;
  reason?: string | null;
  rewardAmount?: number;
  rewardAsset?: AssetSymbol;
  claimExpiresAt?: ISODateTime | null;
  retryLimit?: number | null;
  parentSessionId?: SessionId;
  delegationPolicy?: DelegationPolicy;
  recurringPolicy?: RecurringPolicy;
  lineage?: SubJobLineageMetadata;
  funding?: JobFunding;
  submissionContract?: SubmissionContract;
  schemaContract?: JobSchemaContract;
}

export interface JobsListResponse extends ApiEnvelope {
  jobs: JobSummary[];
  count?: number;
  total?: number;
  limit?: number;
  offset?: number;
  nextOffset?: number | null;
  compact?: boolean;
}

export interface ListJobsOptions {
  wallet?: WalletAddress;
  source?: string;
  category?: string;
  state?: string;
  format?: string;
  limit?: number;
  offset?: number;
}

export interface RecommendationResponse extends ApiEnvelope {
  recommendations?: JobSummary[];
  jobs?: JobSummary[];
}

export interface PreflightResponse extends ApiEnvelope {
  jobId?: JobId;
  eligible?: boolean;
  claimable?: boolean;
  currentWalletCanClaim?: boolean | null;
  reason?: string | null;
  retryLimit?: number | null;
  claimExpiresAt?: ISODateTime | null;
  submissionContract?: SubmissionContract;
  schemaContract?: JobSchemaContract;
}

export interface ValidationResponse<TSubmission = unknown> extends ApiEnvelope {
  valid: boolean;
  submitSafe?: boolean;
  errors?: ApiEnvelope[];
  submission?: TSubmission;
  schemaRef?: BuiltinJobSchemaRef | string;
  schemaValidates?: "payload.submission" | string;
  validationEndpoint?: "POST /jobs/validate-submission" | string;
  submitEndpoint?: "POST /jobs/submit" | string;
  submissionShape?: "direct_schema_object" | string;
  doNotWrapInOutput?: boolean;
  requiredTopLevelKeys?: string[];
  submissionKind?: "structured" | string;
  message?: string;
  code?: string;
  details?: ApiEnvelope;
  path?: string;
  errorPaths?: string[];
  expected?: string;
  expectedPath?: string;
}

export interface InvalidWrappedOutputReadiness extends ApiEnvelope {
  jobId: JobId;
  valid: false;
  submitSafe: false;
  schemaRef?: BuiltinJobSchemaRef | string | null;
  schemaValidates?: "payload.submission" | string;
  code?: string | null;
  message?: string | null;
  path?: string | null;
  received?: string | null;
  hint?: string | null;
  checkedBeforeClaim: true;
  submitAttempted: false;
  validation?: ValidationResponse;
}

export interface SchemaNativeSubmissionReadinessOptions<TProbe extends StructuredSubmission = StructuredSubmission> {
  expectedSchemaRef?: BuiltinJobSchemaRef | string;
  requireInvalidWrapperRejection?: boolean;
  invalidWrappedOutputProbe?: TProbe;
}

export interface SchemaNativeSubmissionReadiness<TSubmission = StructuredSubmission> extends ApiEnvelope {
  jobId: JobId;
  valid: true;
  submitSafe: true;
  schemaRef?: BuiltinJobSchemaRef | string | null;
  schemaValidates?: "payload.submission" | string;
  submissionKind?: "structured" | "raw" | string;
  validatedBeforeClaim: true;
  directValidation: ValidationResponse<TSubmission>;
  invalidWrappedOutput?: InvalidWrappedOutputReadiness | null;
}

export interface ClaimResponse extends SessionRecord {
  sessionId: SessionId;
  jobId: JobId;
  wallet: WalletAddress;
}

export interface SubmitResponse extends SessionRecord {
  sessionId: SessionId;
}

export interface SessionRecord extends ApiEnvelope {
  sessionId: SessionId;
  jobId?: JobId;
  wallet?: WalletAddress;
  status?: string;
  state?: string;
  claimExpiresAt?: ISODateTime | null;
  deadline?: ISODateTime | null;
  claimedAt?: ISODateTime;
  submittedAt?: ISODateTime;
  updatedAt?: ISODateTime;
  parentSessionId?: SessionId;
}

export interface TimelineEntry extends ApiEnvelope {
  id?: string;
  type?: string;
  at?: ISODateTime;
  label?: string;
}

export interface SubJobBudgetSummary extends ApiEnvelope {
  asset: AssetSymbol;
  budgetAmount?: number;
  usedAmount?: number;
  remainingAmount?: number;
  parentBudgetAmount?: number;
  usedBeforeAmount?: number;
  usedAfterAmount?: number;
  remainingAfterAmount?: number;
}

export interface SubJobLineageMetadata extends ApiEnvelope {
  kind?: "sub_job" | string;
  parentSessionId?: SessionId;
  parentJobId?: JobId;
  parentWallet?: WalletAddress;
  depth?: number;
  createdBy?: WalletAddress;
  createdAt?: ISODateTime;
  budget?: SubJobBudgetSummary;
  funding?: ApiEnvelope;
}

export interface SessionLineage extends ApiEnvelope {
  parentSessionId?: SessionId;
  childJobIds?: JobId[];
  childSessionIds?: SessionId[];
  subJobBudget?: SubJobBudgetSummary;
  subJobPolicy?: DelegationPolicy;
}

export interface SessionTimelineResponse extends ApiEnvelope {
  timelineVersion?: string;
  session?: SessionRecord;
  lineage?: SessionLineage;
  stateMachine?: ApiEnvelope;
  timeline: TimelineEntry[];
}

export interface JobTimelineLineage extends ApiEnvelope {
  sessionIds?: SessionId[];
  childJobIds?: JobId[];
  terminalSessionIds?: SessionId[];
}

export interface JobTimelineResponse extends ApiEnvelope {
  timelineVersion?: string;
  job?: JobDefinition;
  lineage?: JobTimelineLineage;
  summary?: ApiEnvelope;
  timeline: TimelineEntry[];
}

export interface JobTimelineOptions {
  limit?: number;
}

export interface SessionListResponse extends ApiEnvelope {
  sessions: SessionRecord[];
  count?: number;
  total?: number;
  limit?: number;
  offset?: number;
  scope?: "wallet" | "operator" | string;
}

export interface DisputeSummary extends ApiEnvelope {
  id: string;
  sessionId?: SessionId;
  status?: string;
  verdict?: string;
}

export interface DisputeListResponse extends ApiEnvelope {
  disputes?: DisputeSummary[];
  count?: number;
}

export interface DisputeVerdictInput {
  verdict: string;
  rationale?: string;
}

export interface SubJobCreateInput extends ApiEnvelope {
  parentSessionId: SessionId;
  id: JobId;
  category: string;
  tier?: string;
  rewardAmount: number | string;
  rewardAsset?: AssetSymbol;
  verifierMode: string;
  verifierTerms?: string[];
  verifierMinimumMatches?: number;
  claimTtlSeconds?: number;
  retryLimit?: number;
}

export interface SubJobListItem extends JobSummary {
  sessions?: SessionRecord[];
}

export type SubJobListResponse = SubJobListItem[];

export interface FireRecurringJobOptions {
  firedAt?: ISODateTime;
  idempotencyKey?: IdempotencyKey;
}

export interface AdminJobCreateInput extends ApiEnvelope {
  id: JobId;
  category: string;
  rewardAmount: number | string;
  rewardAsset?: AssetSymbol;
  verifierMode: string;
  tier?: string;
  retryLimit?: number;
  delegationPolicy?: DelegationPolicy;
  recurring?: boolean;
  recurringPolicy?: RecurringPolicy;
}

export interface AdminSettlementAssetStatus extends ApiEnvelope {
  symbol?: AssetSymbol;
  address?: string;
  assetClass?: string;
  assetId?: number;
  foreignAssetIndex?: number;
  decimals?: number;
  approved?: boolean;
}

export interface AdminPolicyStatus extends ApiEnvelope {
  enabled?: boolean;
  policyAddress?: string;
  paused?: boolean;
  owner?: string;
  pauser?: string;
  settlementReady?: boolean;
  contracts?: {
    escrowCoreAddress?: string;
    agentAccountAddress?: string;
    reputationSbtAddress?: string;
    supportedAssets?: AdminSettlementAssetStatus[];
    [key: string]: unknown;
  };
  roles?: {
    signerAddress?: string;
    signerIsVerifier?: boolean;
    escrowIsServiceOperator?: boolean;
    agentAccountIsServiceOperator?: boolean;
    [key: string]: unknown;
  };
  readErrors?: Array<{
    field?: string;
    message?: string;
    [key: string]: unknown;
  }>;
  risk?: ApiEnvelope;
}

export interface AdminStatusResponse extends ApiEnvelope {
  jobLifecycle?: {
    total?: number;
    claimable?: number;
    open?: number;
    paused?: number;
    archived?: number;
    stale?: number;
    [key: string]: unknown;
  };
  recurringJobs?: ApiEnvelope;
  providerOperations?: ApiEnvelope;
  maintenance?: {
    policy?: AdminPolicyStatus;
    [key: string]: unknown;
  };
}

export type CapabilityGrantStatus = "active" | "revoked";

export interface CapabilityGrantProjection {
  id: string;
  subject: WalletAddress;
  capabilities: string[];
  scope?: string;
  note?: string;
  issuedBy: WalletAddress;
  issuedAt: ISODateTime;
  expiresAt?: ISODateTime;
  status: CapabilityGrantStatus;
  revokedAt?: ISODateTime;
  revokedBy?: WalletAddress;
  revokeNote?: string;
}

export interface ServiceTokenListOptions {
  subject?: WalletAddress;
  status?: CapabilityGrantStatus;
  limit?: number;
  offset?: number;
}

export interface ServiceTokenListItem {
  tokenKind: "service";
  tokenAvailable: false;
  grant: CapabilityGrantProjection;
}

export interface ServiceTokenListResponse extends ApiEnvelope {
  items: ServiceTokenListItem[];
  limit: number;
  offset: number;
}

export interface ServiceTokenIssueInput {
  subject: WalletAddress;
  capabilities: string[];
  scope?: string;
  note?: string;
  expiresAt?: ISODateTime;
  tokenTtlSeconds?: number;
  idempotencyKey?: IdempotencyKey;
}

export interface ServiceTokenRotateInput {
  capabilities?: string[];
  scope?: string;
  note?: string;
  expiresAt?: ISODateTime;
  tokenTtlSeconds?: number;
  revokeNote?: string;
  idempotencyKey?: IdempotencyKey;
}

export interface ServiceTokenRevokeInput {
  note?: string;
  idempotencyKey?: IdempotencyKey;
}

export interface ServiceTokenIssueResponse extends ApiEnvelope {
  token: string;
  tokenType: "Bearer";
  tokenKind: "service";
  tokenAvailable: true;
  wallet: WalletAddress;
  capabilities: string[];
  expiresAt: ISODateTime;
  grant: CapabilityGrantProjection;
  rotatedFrom?: CapabilityGrantProjection;
  usage: { header: string };
}

export interface ServiceTokenRevokeResponse extends ApiEnvelope {
  tokenKind: "service";
  tokenAvailable: false;
  status: "revoked";
  alreadyRevoked: boolean;
  grant: CapabilityGrantProjection;
}

export class AgentPlatformApiError extends Error {
  constructor(options: {
    message: string;
    status: number;
    method: string;
    path: string;
    payload?: unknown;
  });

  name: "AgentPlatformApiError";
  status: number;
  method: string;
  path: string;
  payload?: unknown;
  code?: string;
  details?: unknown;
}

export class AgentPlatformValidationError<TValidation = ValidationResponse> extends Error {
  constructor(options: {
    message: string;
    validation?: TValidation;
  });
  validation?: TValidation;
  code?: string;
  details?: unknown;
}

export class AgentPlatformClient {
  constructor(options?: AgentPlatformClientOptions);

  baseUrl: string;
  token?: string;
  fetchImpl: typeof fetch;

  setToken(token?: string): void;

  getHealth(): Promise<HealthResponse>;
  getOnboarding(): Promise<OnboardingResponse>;
  getDiscoveryManifest(): Promise<DiscoveryManifest>;
  getJobTierLadder(): Promise<JobTierLadderResponse>;
  listStrategies(): Promise<StrategiesResponse>;
  getSessionStateMachine(): Promise<SessionStateMachineResponse>;
  listJobSchemas(): Promise<JobSchemasResponse>;
  getJobSchema(name: string): Promise<JsonObject>;
  getAgentProfile(wallet: WalletAddress): Promise<AgentProfile>;
  listAgents(options?: { limit?: number }): Promise<AgentListResponse>;
  getAgentBadge(sessionId: SessionId): Promise<BadgeResponse>;
  listBadges(options?: { limit?: number }): Promise<BadgeResponse[] | ApiEnvelope>;
  listAlerts(options?: { limit?: number }): Promise<AlertListResponse>;
  listAuditEvents(options?: { limit?: number }): Promise<AuditEventListResponse>;
  listPolicies(): Promise<PolicyListResponse>;
  getPolicy(tag: string): Promise<PolicySummary>;
  proposePolicy(payload: unknown): Promise<PolicySummary>;
  listVerifierHandlers(): Promise<VerifierHandlersResponse>;

  issueNonce(wallet: WalletAddress): Promise<NonceResponse>;
  verifySignature(message: string, signature: string): Promise<AuthSessionResponse>;
  getAuthSession(): Promise<AuthSessionResponse>;

  getAccountSummary(): Promise<AccountSummary>;
  getBorrowCapacity(asset?: AssetSymbol): Promise<BorrowCapacityResponse>;
  getStrategyPositions(): Promise<StrategyPositionsResponse>;
  fundAccount(input: FundAccountInput): Promise<AccountSummary>;
  allocateIdleFunds(input: StrategyMutationInput): Promise<AccountSummary>;
  deallocateIdleFunds(input: StrategyMutationInput): Promise<AccountSummary>;
  sendToAgent(input: SendToAgentInput): Promise<AccountSummary>;
  borrowFunds(input: BalanceMutationInput): Promise<AccountSummary>;
  repayFunds(input: BalanceMutationInput): Promise<AccountSummary>;

  listJobs(options?: ListJobsOptions): Promise<JobsListResponse>;
  listClaimableJobs(options?: ListJobsOptions): Promise<JobsListResponse>;
  getJobDefinition(jobId: JobId): Promise<JobDefinition>;
  getRecommendations(): Promise<RecommendationResponse>;
  preflightJob(jobId: JobId): Promise<PreflightResponse>;
  validateJobSubmission<TSubmission extends StructuredSubmission = StructuredSubmission>(
    jobId: JobId,
    submission: TSubmission
  ): Promise<ValidationResponse<TSubmission>>;
  assertValidJobSubmission<TSubmission extends StructuredSubmission = StructuredSubmission>(
    jobId: JobId,
    submission: TSubmission
  ): Promise<ValidationResponse<TSubmission>>;
  assertSchemaNativeSubmissionReady<TSubmission extends StructuredSubmission = StructuredSubmission>(
    jobId: JobId,
    submission: TSubmission,
    options?: SchemaNativeSubmissionReadinessOptions
  ): Promise<SchemaNativeSubmissionReadiness<TSubmission>>;
  claimJobAfterValidation<TSubmission extends StructuredSubmission = StructuredSubmission>(
    jobId: JobId,
    submission: TSubmission,
    idempotencyKey?: IdempotencyKey
  ): Promise<ClaimResponse>;
  claimJob(jobId: JobId, idempotencyKey?: IdempotencyKey): Promise<ClaimResponse>;
  submitWork<TSubmission extends StructuredSubmission = StructuredSubmission>(
    sessionId: SessionId,
    submission: string | TSubmission
  ): Promise<SubmitResponse>;
  submitValidatedWork<TSubmission extends StructuredSubmission = StructuredSubmission>(
    jobId: JobId,
    sessionId: SessionId,
    submission: TSubmission
  ): Promise<SubmitResponse>;
  getSession(sessionId: SessionId): Promise<SessionRecord>;
  getSessionTimeline(sessionId: SessionId): Promise<SessionTimelineResponse>;
  getJobTimeline(jobId: JobId, options?: JobTimelineOptions): Promise<JobTimelineResponse>;
  listSessions(options?: { limit?: number; jobId?: JobId }): Promise<SessionListResponse>;
  listAdminSessions(options?: {
    limit?: number;
    jobId?: JobId;
    wallet?: WalletAddress;
  }): Promise<SessionListResponse>;
  listSubJobs(parentSessionId: SessionId): Promise<SubJobListResponse>;
  createSubJob(payload: SubJobCreateInput): Promise<JobDefinition>;

  listDisputes(options?: { limit?: number }): Promise<DisputeListResponse>;
  getDispute(id: string): Promise<DisputeSummary>;
  submitDisputeVerdict(id: string, input: DisputeVerdictInput): Promise<DisputeSummary>;
  releaseDisputeStake(id: string, payload?: unknown): Promise<DisputeSummary>;

  runVerifier(sessionId: SessionId, evidence?: string, metadataURI?: string): Promise<ApiEnvelope>;
  replayVerifier(sessionId: SessionId): Promise<ApiEnvelope>;
  getVerifierResult(sessionId: SessionId): Promise<ApiEnvelope>;

  createJob(payload: AdminJobCreateInput): Promise<JobDefinition>;
  fireRecurringJob(templateId: JobId, options?: FireRecurringJobOptions): Promise<JobDefinition>;
  pauseRecurringJob(templateId: JobId, options?: { idempotencyKey?: IdempotencyKey }): Promise<ApiEnvelope>;
  resumeRecurringJob(templateId: JobId, options?: { idempotencyKey?: IdempotencyKey }): Promise<ApiEnvelope>;
  getAdminStatus(): Promise<AdminStatusResponse>;

  listServiceTokens(options?: ServiceTokenListOptions): Promise<ServiceTokenListResponse>;
  issueServiceToken(input: ServiceTokenIssueInput): Promise<ServiceTokenIssueResponse>;
  rotateServiceToken(
    grantId: string,
    input?: ServiceTokenRotateInput
  ): Promise<ServiceTokenIssueResponse>;
  revokeServiceToken(
    grantId: string,
    input?: ServiceTokenRevokeInput
  ): Promise<ServiceTokenRevokeResponse>;

  request<T = unknown>(path: string, options?: RequestOptions): Promise<T>;
}
