import type { SessionDetail } from "./types";

// TODO(data): wire to useApi("/sessions") once backend emits the list.
// Drill-in swaps to useApi(`/sessions/${id}`) for drawer. Fixture covers
// every state so the filter rail and drawer can be exercised end-to-end.

export const SESSIONS: SessionDetail[] = [
  {
    id: "sess_a91c…4412",
    runRef: "run-2742",
    job: { title: "gov-review: proposal 0x7a0c abstract", meta: "job-0418 · writer-gov · T2" },
    worker: { handle: "writer-gov-1", address: "0xFd2E…6519", initials: "FD", tone: "sage" },
    state: "approved",
    escrow: { amount: "25.00", asset: "DOT" },
    verifierMode: "semantic",
    age: "00:08:14",
    lastEvent: {
      text: "Verified · awaiting cosign",
      meta: "14:28:03 · 4/5 checks pass",
      tone: "accent",
    },
    openedAt: "14:20:25 UTC",
    policy: "writer-gov/cited@v3",
    receipt: "r_4e12a",
    lifecycle: [
      { label: "Discoverable", meta: "14:20:25", state: "done" },
      { label: "Claimed", meta: "14:23:53 · by you", state: "done" },
      { label: "Submitted", meta: "14:27:45 · 412B evidence", state: "done" },
      { label: "Verified", meta: "14:28:03 · 4/5 pass", state: "current", tone: "accent" },
      { label: "Settled", meta: "—", state: "pending" },
    ],
    movements: [
      {
        at: "14:20:25",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "25.00 DOT",
        tx: "0x3f…c1",
      },
      {
        at: "14:23:53",
        label: "stake.locked",
        from: "worker",
        to: "AgentAccountCore",
        amount: "5.00 DOT",
        tx: "0xaa…02",
        tone: "accent",
      },
      {
        at: "14:27:45",
        label: "evidence.submitted",
        from: "writer-gov-1",
        to: "verifier-2",
        amount: "—",
        tx: "sha256 0x9c…41",
      },
    ],
    payouts: [
      {
        party: "writer-gov-1",
        role: "worker",
        amount: "12.50 DOT",
        at: "pending",
        tx: "—",
      },
      {
        party: "verifier-2",
        role: "verifier",
        amount: "7.50 DOT",
        at: "pending",
        tx: "—",
      },
      {
        party: "treasury",
        role: "treasury",
        amount: "5.00 DOT",
        at: "pending",
        tx: "—",
      },
    ],
    evidenceHref: "/runs/run-2742#evidence",
    verifierHref: "/runs/run-2742#verifier",
  },
  {
    id: "sess_a90b…31fa",
    runRef: "run-2738",
    job: { title: "docs refresh — v3.1", meta: "job-0411 · writer-gov · T1" },
    worker: { handle: "writer-gov-1", address: "0xFd2E…6519", initials: "FD", tone: "sage" },
    state: "settled",
    escrow: { amount: "18.00", asset: "DOT" },
    verifierMode: "semantic",
    age: "01:22:04",
    lastEvent: {
      text: "Settled · receipt signed",
      meta: "13:58 UTC · r_4e0f8",
      tone: "accent",
    },
    openedAt: "13:04:22 UTC",
    policy: "writer-gov/cited@v3",
    receipt: "r_4e0f8",
    lifecycle: [
      { label: "Discoverable", meta: "13:04:22", state: "done" },
      { label: "Claimed", meta: "13:12:10", state: "done" },
      { label: "Submitted", meta: "13:27:19", state: "done" },
      { label: "Verified", meta: "13:28:41 · 5/5", state: "done" },
      { label: "Settled", meta: "13:58:02 · r_4e0f8", state: "done" },
    ],
    movements: [
      {
        at: "13:04:22",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "18.00 DOT",
        tx: "0x1e…40",
      },
      {
        at: "13:58:02",
        label: "settle.finalized",
        from: "AgentAccountCore",
        to: "writer-gov-1",
        amount: "9.00 DOT",
        tx: "0xbd…9a",
        tone: "accent",
      },
      {
        at: "13:58:03",
        label: "settle.finalized",
        from: "AgentAccountCore",
        to: "verifier-2",
        amount: "5.40 DOT",
        tx: "0xc1…4b",
        tone: "accent",
      },
      {
        at: "13:58:03",
        label: "settle.finalized",
        from: "AgentAccountCore",
        to: "treasury",
        amount: "3.60 DOT",
        tx: "0xd2…17",
      },
    ],
    payouts: [
      {
        party: "writer-gov-1",
        role: "worker",
        amount: "9.00 DOT",
        at: "13:58:02",
        tx: "0xbd…9a",
      },
      {
        party: "verifier-2",
        role: "verifier",
        amount: "5.40 DOT",
        at: "13:58:03",
        tx: "0xc1…4b",
      },
      {
        party: "treasury",
        role: "treasury",
        amount: "3.60 DOT",
        at: "13:58:03",
        tx: "0xd2…17",
      },
    ],
    evidenceHref: "/runs/run-2738#evidence",
    verifierHref: "/runs/run-2738#verifier",
  },
  {
    id: "sess_a8f7…00ad",
    runRef: "run-2739",
    job: { title: "handoff-sig verify: batch #214", meta: "job-0414 · coding-hand · T2" },
    worker: { handle: "coding-hand-3", address: "0x4F88AD…19c0", initials: "CH", tone: "clay" },
    state: "disputed",
    escrow: { amount: "40.00", asset: "DOT" },
    verifierMode: "paired-hash",
    age: "01:52:41",
    ageStale: true,
    lastEvent: {
      text: "Dispute opened · signature mismatch",
      meta: "14:02:09 · r_4e10c",
      tone: "warn",
    },
    openedAt: "12:30:00 UTC",
    policy: "claim/handoff-sig@v2",
    lifecycle: [
      { label: "Discoverable", meta: "12:30:00", state: "done" },
      { label: "Claimed", meta: "12:42:15", state: "done" },
      { label: "Submitted", meta: "13:51:02", state: "done" },
      { label: "Verified", meta: "14:02:09 · disputed", state: "current", tone: "warn" },
      { label: "Settled", meta: "—", state: "pending" },
    ],
    movements: [
      {
        at: "12:30:00",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "40.00 DOT",
        tx: "0x9a…22",
      },
      {
        at: "12:42:15",
        label: "stake.locked",
        from: "coding-hand-3",
        to: "AgentAccountCore",
        amount: "5.00 DOT",
        tx: "0xb1…0c",
        tone: "accent",
      },
      {
        at: "14:02:14",
        label: "stake.frozen",
        from: "AgentAccountCore",
        to: "dispute-escrow",
        amount: "45.00 DOT",
        tx: "0xe8…11",
        tone: "warn",
      },
    ],
    payouts: [],
    evidenceHref: "/runs/run-2739#evidence",
    verifierHref: "/runs/run-2739#verifier",
    disputeHref: "/disputes/d_4e10c",
  },
  {
    id: "sess_a8e4…77b1",
    runRef: "run-2711",
    job: { title: "writer: OP-14 cited summary", meta: "job-0396 · writer-gov · T2" },
    worker: { handle: "writer-gov-2", address: "0x5C17F0…4a90", initials: "W2", tone: "clay" },
    state: "slashed",
    escrow: { amount: "11.00", asset: "DOT" },
    verifierMode: "semantic",
    age: "2 days",
    lastEvent: {
      text: "Upheld · stake slashed to treasury",
      meta: "Apr 22 10:22 · r_4df10",
      tone: "bad",
    },
    openedAt: "Apr 22 · 10:00 UTC",
    policy: "writer-gov/cited@v3",
    receipt: "r_4df10",
    lifecycle: [
      { label: "Discoverable", meta: "Apr 22 10:00", state: "done" },
      { label: "Claimed", meta: "Apr 22 10:02", state: "done" },
      { label: "Submitted", meta: "Apr 22 10:05", state: "done" },
      { label: "Verified", meta: "Apr 22 10:06 · disputed", state: "done", tone: "warn" },
      { label: "Slashed", meta: "Apr 22 10:22", state: "done", tone: "bad" },
    ],
    movements: [
      {
        at: "Apr 22 10:00",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "11.00 DOT",
        tx: "0x77…12",
      },
      {
        at: "Apr 22 10:22",
        label: "stake.slashed",
        from: "worker-portion",
        to: "treasury",
        amount: "7.00 DOT",
        tx: "0x88…34",
        tone: "bad",
      },
      {
        at: "Apr 22 10:22",
        label: "stake.paid",
        from: "verifier-portion",
        to: "gov-review-2",
        amount: "3.00 DOT",
        tx: "0x99…56",
      },
    ],
    payouts: [
      {
        party: "treasury",
        role: "treasury",
        amount: "7.00 DOT",
        at: "Apr 22 10:22",
        tx: "0x88…34",
      },
      {
        party: "gov-review-2",
        role: "verifier",
        amount: "3.00 DOT",
        at: "Apr 22 10:22",
        tx: "0x99…56",
      },
    ],
    evidenceHref: "/runs/run-2711#evidence",
    verifierHref: "/runs/run-2711#verifier",
    disputeHref: "/disputes/d_4df10",
  },
  {
    id: "sess_a91a…41ab",
    runRef: "run-2744",
    job: { title: "docs refresh — v3.2", meta: "job-0417 · writer-gov · T1" },
    worker: { handle: "writer-gov-1", address: "0xFd2E…6519", initials: "FD", tone: "sage" },
    state: "submitted",
    escrow: { amount: "14.00", asset: "DOT" },
    verifierMode: "semantic",
    age: "00:04:47",
    lastEvent: {
      text: "Submitted · verifier queued",
      meta: "14:11:18 · semantic mode",
    },
    openedAt: "14:06:30 UTC",
    policy: "writer-gov/cited@v3",
    lifecycle: [
      { label: "Discoverable", meta: "14:06:30", state: "done" },
      { label: "Claimed", meta: "14:07:02", state: "done" },
      { label: "Submitted", meta: "14:11:18", state: "current", tone: "accent" },
      { label: "Verified", meta: "—", state: "pending" },
      { label: "Settled", meta: "—", state: "pending" },
    ],
    movements: [
      {
        at: "14:06:30",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "14.00 DOT",
        tx: "0x42…90",
      },
      {
        at: "14:07:02",
        label: "stake.locked",
        from: "writer-gov-1",
        to: "AgentAccountCore",
        amount: "3.00 DOT",
        tx: "0x3a…55",
      },
    ],
    payouts: [
      {
        party: "writer-gov-1",
        role: "worker",
        amount: "7.00 DOT",
        at: "pending",
        tx: "—",
      },
      {
        party: "verifier-2",
        role: "verifier",
        amount: "4.20 DOT",
        at: "pending",
        tx: "—",
      },
      {
        party: "treasury",
        role: "treasury",
        amount: "2.80 DOT",
        at: "pending",
        tx: "—",
      },
    ],
    evidenceHref: "/runs/run-2744#evidence",
    verifierHref: "/runs/run-2744#verifier",
  },
  {
    id: "sess_a89c…22ce",
    runRef: "run-2705",
    job: { title: "settle r_4dab1 — 58 DOT", meta: "job-0378 · settle-dual-sign · T3" },
    worker: { handle: "ops-migrator-1", address: "0xB2C7E1…ad14", initials: "OM", tone: "ink" },
    state: "rejected",
    escrow: { amount: "58.00", asset: "DOT" },
    verifierMode: "deterministic",
    age: "yesterday",
    lastEvent: {
      text: "Rejected · receipt hash mismatch",
      meta: "Apr 22 14:50 · verifier-2",
      tone: "warn",
    },
    openedAt: "Apr 22 · 14:44 UTC",
    policy: "settle/receipt-hash-match@v2",
    lifecycle: [
      { label: "Discoverable", meta: "Apr 22 14:44", state: "done" },
      { label: "Claimed", meta: "Apr 22 14:46", state: "done" },
      { label: "Submitted", meta: "Apr 22 14:48", state: "done" },
      { label: "Verified", meta: "Apr 22 14:50 · rejected", state: "done", tone: "warn" },
      { label: "Settled", meta: "escrow returned", state: "done" },
    ],
    movements: [
      {
        at: "Apr 22 14:44",
        label: "escrow.funded",
        from: "treasury",
        to: "AgentAccountCore",
        amount: "58.00 DOT",
        tx: "0xa2…11",
      },
      {
        at: "Apr 22 14:50",
        label: "escrow.returned",
        from: "AgentAccountCore",
        to: "treasury",
        amount: "58.00 DOT",
        tx: "0xaf…20",
      },
    ],
    payouts: [],
    evidenceHref: "/runs/run-2705#evidence",
    verifierHref: "/runs/run-2705#verifier",
  },
];
